#!/usr/bin/env bash
# Configure Nginx server that redirecting to another page
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
string_to_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/@eliasd342 permanent;" 
sudo sed -i "s/server_name _;/$string_to_replacement/" /etc/nginx/sites-enabled/default
sudo service nginx restart
