#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page that contains
# the string Ceci n'est pas une page

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
string_to_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/@eliasd342 permanent;"
sudo sed -i "s/server_name _;/$string_to_replacement/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" > /var/www/html/custom404.html
string_to_replacement="listen 80 default_server;\n\terror_page 404 \/cutom404.html;\n\tlocation = \/cutom404.html {\n\t\troot \/var\/www\/html; \n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_to_replacement/" /etc/nginx/sites-enabled/default
sudo service nginx restart
