#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page that contains
# the string Ceci n'est pas une page

# update and install
sudo apt-get update
sudo apt-get -y install nginx

# write and redirect
echo "Hello World!" | sudo tee /var/www/html/index.html
string_to_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/@eliasd342 permanent;"
sudo sed -i "s/server_name _;/$string_to_replacement/" /etc/nginx/sites-enabled/default
# Error page and redirect
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
string_to_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_to_replacement/" /etc/nginx/sites-enabled/default
# restart nginx
sudo service nginx restart