#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page that contains
# the string Ceci n'est pas une page
apt-get update
apt-get install -y nginx
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
ufw allow 'Nginx HTTP'
echo "Hello World!" > /etc/nginx/html/index.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/channel/UC0ypST9g7cIDMjgGq9cgkJg permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom404.html
sed -i '/listen 80 default_server;/a error_page/cutom404.html; location = /cutom404.html {
 root /usr/share/nginx/html; internal; }' /etc/nginx/sites-available/default
service nginx restart
