#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on

# update and install
sudo apt-get -y update
sudo apt-get -y install nginx

#create and write
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# redirect
sed -i '/server_name _/a location /redirect_me { rewrite ^ https://www.youtube.com/@eliasd342 permanent; }' /etc/nginx/sites-available/default
sed -i '/server_name _/a error_page 404 /404.html { root /var/www/html/; internal; }' /etc/nginx/sites-available/default

sudo sed -i '/server_name _/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

#restart server
sudo service nginx start
