#!/usr/bin/env bash
# This script

# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

FILE="/var/run/myscript.pid"
remove() {
	rm $FILE
	exit
}

echo "$$" > $FILE

while 'true'
do
	echo "To infinity and beyond"
	trap 'echo "I hate the kill command" && remove' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'remove' SIGQUIT
done
