#!/usr/bin/env bash
# This script is displays numbers from 1 to 100
# Displays FizzBuzz when the number is a multiple of 3 and 5

# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number

a=1
while [ $a -le 100 ]
do
        if [ $((a % 15)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((a % 5)) -eq 0 ]
	then
		echo "Buzz"
	elif [ $((a % 3)) -eq 0 ]
	then
		echo "Fizz"
	else
		echo "$a"
	fi
	((a++)) 
done
