#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# but for the 9th iteration, displays Best School and then Hi on a new line
a=0
while [ $a -lt 10 ]
do
        echo "Best School"
        ((a++))
	if [ $a == 9 ]
	then
		echo "Hi"
	fi
done
